### ISSUE TITLE
Features requested to support document generation and fine-grained development control

### ISSUE THREAD

**Issue by greenc-FNAL** [FNALssi/spack-mpd#11]
- [x] Support for per-package variants (e.g. `cetmodules +versioned-docs`).
- [x] ~Support for first-line build dependencies such as `py-sphinx` and friends.~ (already present but obscured by lack of the above).
- [x] Merge in non-spec (e.g. `packages:`) clauses from `spack.yaml` of supplied environment.
- [x] Support for virtual dependencies rather than the concrete ones (e.g. `tbb` instead of `intel-tbb-oneapi`).
- [x] Document the above

**Comment by knoepfel** [comment]
General and per-package variants are supported as of committed https://github.com/FNALssi/spack-mpd/commit/d048197c2d9f001272290f11bdd127cabecdffcc.  The convention:

```console
$ spack mpd new-project --name NAME -E ... \
    <general variants ...> \
    <developed-package variants ...> \
    <dependency variants ...>
```

where

- general variants are not prefaced with a package name, but applied to any developed package that supports them (e.g. `cxxstd=20`, `generator=ninja`,`%gcc@14`)
- developed-package variants apply to a specific developed package and are of the form `<pkg>[@version] +var1 var2=val ...`
- dependency variants are of the standard Spack form  `^dep@...`  where the dep package and its variants are added to the `packages:` block of the environment configuration

At the moment, `@`-prefixed version strings, compiler specifications, Boolean variants, and key-value pair variants are supported.  Also supported are propagated variants, where two syntactic tokens are specified instead of one (e.g. `++var1` and `cxxstd==20` vs. `+var1` and `cxxstd=20`).

**Comment by greenc-FNAL** [comment]
`spack mpd new-project` attempts to ensure that the first-line dependencies of each package to be developed are installed, no? I thought it would be necessary to do the same for build dependencies.

**Comment by greenc-FNAL** [comment]
It's possible I didn't see it because the parent environment specified `cetmodules` without `+versioned-docs`, and previously MPD wasn't able to add `+versioned-docs` to the development spec. I will double check when testing the [new feature](https://github.com/FNALssi/spack-mpd/issues/11#issuecomment-2484332939) (today, I hope), but I understand that you're telling me I will see the desired build-dependencies at this time. In which case, :tada:!

**Comment by knoepfel** [comment]
### Regarding virtual dependencies

@greenc-FNAL, some nuances need to be sorted out with this item:

>  - Support for virtual dependencies rather than the concrete ones (e.g. tbb instead of intel-tbb-oneapi).

To form the list of root specs for the development environment, the following bootstrap procedure happens:

1.  A named environment is created with the same name as the MPD project name.  The named environment includes any concrete environments specified by `new-project -E <env>`.  The root specs of the named environment are the packages under development.
2. After concretization, the named environment is copied to an anonymous development environment.
3. The first-line **_concretized_** (_not_ virtual) dependencies from (2) are added as root specs to the development environment, which is reconcretized.
4. The packages under development are then removed from the root spec list of the development environment, which is then reconcretized one last time.

This means that the root specs of the generated development environment will never be virtual packages.  And this should be fine because they will be consistent with whatever was concretized in the named environment.

Suppose, however, a package _under development_ (or one of its dependencies) depends on a virtual package.  Then you might want to specify what providers should satisfy the virtual-package dependencies.

Here is my suggested behavior:

5. The named environment in (1) above will, by default, be concretized with the `packages.all.providers` configuration parameter as specified in the `new-project -E <env>` environments.
6.  The named environment's `packages.all.providers` parameter will be updated according to the `-E` order specified on the command-line.
7.  Further virtual-package specifications will be possible through a command-line interface.  The command-line interface specification takes precedence over any package specifications originating from (5) or (6).

**Comment by knoepfel** [comment]
> 7. Further virtual-package specifications will be possible through a command-line interface. The command-line interface specification takes precedence over any package specifications originating from (5) or (6).

Looks like the command-line interface should be (e.g.) `^[virtuals=tbb] intel-tbb-oneapi`, which is consistent with what is expected of the `spack spec` CLI ([see the example in the documentation](https://spack.readthedocs.io/en/latest/packaging_guide.html#providing-multiple-virtuals-simultaneously)).

**Comment by knoepfel** [comment]
## Merging packages from supplied environments

Item 3 above (merging `packages:` clauses from the `spack.yaml` file of supplied environments) is supported as of commit https://github.com/FNALssi/spack-mpd/commit/8e535ac7fd513104e33ab98ba1091f21a0307c27.  The behavior is:

1. The `packages:` configurations from environments supplied by `-E` are inserted into the project environment.
2. If multiple environments are supplied, those specified later in the command line overwrite the relevant configuration parameters of environments earlier in the command line.  For example, if the configuration of environment `first` is `{"a": 1, "b": 2}` and that of environment `second` is `{"b": 3, "c": 4}`, the merged configuration will be `{"a": 1, "b": 3, "c": 4}`.
3. Additional dependency constraints as specified on the command line (via `^dep...`) will overwrite the relevant parameters from the merged configuration in (2) above.
4. No attempt is made to merge configuration parameters for the same package.

## Supporting virtual packages

Virtual packages are supported as of commit https://github.com/FNALssi/spack-mpd/commit/3fb2760ca9e3d3049f6f4465808b6e668bb4321f.  All virtual package specifications are merged according to the behavior mentioned immediately above.  The command-line interface for specifying a virtual dependency is (e.g.):

```console
$ spack mpd new-project --name <NAME> ... ^[virtuals=tbb] intel-tbb-oneapi 
```

or for an already-existing and selected project:

```console
$ spack mpd refresh ^[virtuals=tbb] intel-tbb-oneapi 
```
